docker-host-stats:
  image: docker-host-stats
  tty: true
  command: -f 30 -cmdn
  links:
    - "cadvisor:cadvisor"
  net: "container:cadvisor"
  volumes:
    - /proc:${PROCPATH}:ro

cadvisor:
  image: google/cadvisor:v0.23.2
  labels:
    io.rancher.scheduler.global: "true"
    io.rancher.scheduler.affinity:host_label_ne: ${HOST_STATS_EXCLUDE_LABEL}
    io.rancher.sidekicks: docker-host-stats
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  ports:
    - "9090:8080"
